## NumPy

* NumPy stands for numerical Python, a Python library that focuses on scientific computing.
* NumPy provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

### Installing NumPy

Use the following command to install NumPy:

```bash
pip install numpy
```

### Importing NumPy

To use NumPy in your Python script, we need to import it at the beginning of our code:
```bash
import numpy as np
```

### NumPy Arrays

The core feature of NumPy is its N-dimensional array object, or ndarray. NumPy arrays are more efficient than Python's built-in lists for numerical operations.

We can create NumPy arrays using various functions:


In [1]:
import numpy as np

# Create a 1D array
array1d = np.array([1, 2, 3, 4, 5])
print(array1d)

[1 2 3 4 5]


In [2]:
# Create a 2D array
array2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array2d)

[[1 2 3]
 [4 5 6]]


In [3]:
# Create a 3D array
array3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Creating Arrays with Built-in Functions

NumPy has several functions to create arrays with specific patterns.

*   `np.zeros(shape)`: Creates an array of zeros with the given shape.
*   `np.ones(shape)`: Creates an array of ones.
*   `np.random(shape)`: Creates an array with random values.
*   `np.arange(start, stop, step)`: Creates an array with a range of values.
*   `np.linspace(start, stop, num)`: Creates an array with evenly spaced values.

In [4]:
zeros = np.zeros((3, 3))  # 3x3 array of zeros
print(zeros)  # [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
ones = np.ones((2, 3))  # 2x3 array of ones
print(ones)  # [[1, 1, 1], [1, 1, 1]]

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
random_array = np.random.random((2, 2))
print(random_array)

[[0.84779133 0.85102614]
 [0.48980327 0.93522891]]


In [7]:
range_array = np.arange(0, 10, 2)  # Array from 0 to 8 with step 2
print(range_array)  # [0, 2, 4, 6, 8]

[0 2 4 6 8]


In [8]:
linspace_array = np.linspace(0, 10, 5)  # 5 evenly spaced values from 0 to 10
print(linspace_array)  # [0, 2.5, 5, 7.5, 10]

[ 0.   2.5  5.   7.5 10. ]


#### Array Attributes

We can get information about the array using attributes:

In [9]:
array = np.array([1, 2, 3])
print(array.shape)     # Output: (3,)
print(array.ndim)      # Output: 1
print(array.dtype)     # Output: int64

(3,)
1
int32


#### Indexing and Slicing

We can access elements, rows, or columns of an array using indexing and slicing.

In [10]:
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Indexing
print(my_array[0, 1])  # 2 (first row, second column)

2


In [11]:
# Slicing rows and columns
print(my_array[0, :])  # [1, 2, 3] (first row)
print(my_array[:, 1])  # [2, 5, 8] (second column)

[1 2 3]
[2 5 8]


In [12]:
# Slicing a subarray
print(my_array[0:2, 1:3])  # [[2, 3], [5, 6]]

[[2 3]
 [5 6]]


#### Basic Operations with NumPy Arrays

NumPy allows you to perform element-wise operations, such as addition, subtraction, multiplication, and division, as well as mathematical functions.

In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
result = arr1 + arr2
print(result)  # [5, 7, 9]

[5 7 9]


In [14]:
# Element-wise multiplication
result = arr1 * arr2
print(result)  # [4, 10, 18]

[ 4 10 18]


In [15]:
# Element-wise division
result = arr2 / arr1
print(result)  # [4, 2.5, 2]

[4.  2.5 2. ]


In [16]:
# Mathematical functions
result = np.sin(arr1)
print(result)  # [sin(1), sin(2), sin(3)]

[0.84147098 0.90929743 0.14112001]


In [17]:
# Square root of each element
sqrt_array = np.sqrt(arr2)
print(sqrt_array)

[2.         2.23606798 2.44948974]


#### Array Reshaping

In [18]:
new_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = new_array.reshape(2, 3)
print(new_array)
print(reshaped_array)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


#### Linear Algebra Operations

In [19]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[2, 3], [4, 5]])

# Matrix multiplication
matmul = np.dot(matrix1, matrix2)
print(matmul)

[[10 13]
 [22 29]]


In [20]:
# Inverse of a matrix
inverse = np.linalg.inv(matrix1)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


#### Transpose

We can transpose an array, which swaps rows with columns:

In [21]:
array = np.array([[1, 2, 3], [4, 5, 6]])
transposed_array = array.T
print(array)
print(transposed_array)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
